config {
  type: "view",
  schema: "spotify",
  name: "plays_recent"
}

select
  played_at,
  datetime(played_at, "Asia/Tokyo") as played_at_jst,
  date(played_at, "Asia/Tokyo") as played_date_jst,
  format_timestamp('%a', played_at, 'Asia/Tokyo') as weekday_jst,
  user_id,
  track_id,
  track_name,
  artist_name,
  album_id,
  album_name,
  album_image_url,
  duration_ms,
  context_type,
  context_uri
from ${ref("plays")}
where played_at >= timestamp_sub(current_timestamp(), interval 90 day)
order by played_at desc
